version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: juan
      POSTGRES_PASSWORD: juan
      POSTGRES_DB: yape
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
